// Generador de buffer MP4 binario válido estándar (ISO Base Media File Format)
function getValidMp4Buffer() {
  // Archivo MP4 base válido codificado en base64 (H.264/AAC contenedor estándar)
  const validMp4Base64 = 
    'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAAAAxtZGF0AAAAAAAA' +
    'AAABAAABbW9vdgAAAGxtdmhkAAAAAM33rPjN96z4AAAD6AAAA+gAAAEAAAEAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0cmFrAAAAXHRraGQA' +
    'AAAAzfes+M33rPgAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAA' +
    'EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAQAAAAAAAABtZGlhAAAAIG1kaGQAAAAA' +
    'zfes+M33rPgAAAPoAAAD6AAAAAAAAAAAAAAANGWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl' +
    'b0hhbmRsZXIAAAAAbWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcadByZWYAAAAU' +
    'dXJsIAAAAAEAAAAAAAAAAAAAOHN0YmwAAABTc3RzZAAAAAAAAAABAAAAQ2F2YzEAAAAAAAAAAQAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAQAAAAAAAAAAAAAAABhhdmNDAWQAJf/4ABhnZAEsp' +
    '4A8A/8BAwAAA+gAAAD6AQwEAaA8AAAAEHN0dHMAAAAAAAAAAAAAAAAcc3RzYwAAAAAAAAABAAAAAQAAAA' +
    'EAAAABAAAAHHN0c3oAAAAAAAAAAAAAAAAAAAAAAAAAABRzdGNvAAAAAAAAAAEAAAA4';

  return Buffer.from(validMp4Base64, 'base64');
}

module.exports = { getValidMp4Buffer };
